USE TEMP;
SELECT * FROM TEMP.ACCOUNT_DETAILS;

SELECT * FROM TEMP.CUSTOMER;

DESC ACCOUNT_DETAILS;

-- ADD COLUMN
ALTER TABLE ACCOUNT ADD INTEREST FLOAT NOT NULL DEFAULT 0;

-- MODIFY DATA TYPE
ALTER TABLE ACCOUNT MODIFY INTEREST DOUBLE NOT NULL DEFAULT 0;

-- CHANGE COLUMN - RENAME COLUMN
ALTER TABLE ACCOUNT CHANGE COLUMN INTEREST SAVING_INTEREST FLOAT NOT NULL DEFAULT 0;

-- DROP COLUMN
ALTER TABLE ACCOUNT DROP COLUMN SAVING_INTEREST;

-- RENAME TABLE NAME
ALTER TABLE ACCOUNT RENAME TO ACCOUNT_DETAILS;

-- UPDATE
UPDATE CUSTOMER SET ADDRESS='MUMBAI', GENDER='M' WHERE ID=121;

-- UPDATE MULTIPLE ROW
-- SET SQL_SAFE_UPDATE = 0;
UPDATE CUSTOMER SET PINCODE = 110000;
UPDATE CUSTOMER SET PINCODE = PINCODE + 1;

-- DELETE 
DELETE FROM CUSTOMER WHERE ID=1;

-- DELETE FROM ORDER_DETAILS TABLE
DELETE FROM ORDER_DETAILS WHERE ORDER_ID=1;
-- DELETE ALL ROWS FROM CUSTOMER TABLE 
DELETE FROM CUSTOMER;
TRUNCATE TABLE CUSTOMER;

-- REPLACE (three ways to use REPLACE QUERY)
REPLACE INTO CUSTOMER (ID, CNAME, GENDER) VALUES(1, 'Mina Kumari', 'F');
-- act as a insert query
REPLACE INTO CUSTOMER (ID, CNAME, GENDER) VALUES(7, 'Minakshi Kumari', 'F');
-- act as a update query
REPLACE INTO CUSTOMER SET ID=8, CNAME='Monika Batra', GENDER='F';

REPLACE INTO CUSTOMER (ID, CNAME, GENDER)
	SELECT ID, CNAME, GENDER 
    FROM CUSTOMER WHERE ID = 2;






